defaults: &defaults
  adapter:  mysql2
  encoding: utf8
  username: root
  password: testrootpassword
  pool: 10
  reconnect: true

development: 
  <<: *defaults
  database: peatio_development

test:
  <<: *defaults
  database: peatio_test

production: 
  <<: *defaults
  database: peatio_production
